-- Snowflake MERGE template
MERGE INTO ANALYTICS.POS_KPIS t
USING TEMP_KPIS s
ON t.MINUTE = s.MINUTE
WHEN MATCHED THEN UPDATE SET
  t.REVENUE_MIN = s.REVENUE_MIN,
  t.ITEMS_MIN = s.ITEMS_MIN
WHEN NOT MATCHED THEN INSERT (MINUTE, REVENUE_MIN, ITEMS_MIN)
VALUES (s.MINUTE, s.REVENUE_MIN, s.ITEMS_MIN);
